### ISSUE TITLE
Outstanding tasks for manipulation tutorials

### ISSUE THREAD

**Issue by mabelzhang** [Field-Robotics-Lab/dave#142]
(Post-release 4.0.0 okay)

### Common to all 5 manipulation tutorials below
- [x] (#150) Move associated files in `uuv_dave` out of `legacy/`
   - Launch files go to `examples/dave_demo_launch`?
   - Plugins go to `gazebo/.....`? Can't guess the right subdirectory
- [x] ~~Fix tf spam - I don't remember if these were resolved in other parts of the repo. Am I the only one getting these?~~ Now tracked in #152
   ```
   [ WARN] [1627632533.852584126, 262.972000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame rexrov/base_link_ned at time 262.972000 according to authority unknown_publisher
   Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame rexrov/base_link_ned at time 262.972000 according to authority /gazebo
            at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp
   ```

### Each tutorial specifically

- [x] https://github.com/Field-Robotics-Lab/dave/wiki/Swapping-out-the-Oberon7-arm-with-another-manipulator/
See above. Update: `uuv_predator.launch` had already been copied to `rexrov_predator.launch` and works.
- [x] https://github.com/Field-Robotics-Lab/dave/wiki/Manipulator-Force-Feedback/
   - [x] (#150) See above
- [x] https://github.com/Field-Robotics-Lab/dave/wiki/Electrical-Plug-Mating-Plugin/
   - [x] (#149) Move `uuv_mating`, in addition to associated files in `uuv_dave`, out of `legacy/`. Files are listed here https://github.com/Field-Robotics-Lab/dave/pull/40.
   - [x] Tutorial doesn’t say how to actually move the robot. Joystick presumably. Should link to a page detailing joystick control for RexROV and the Oberon7.
- [x] https://github.com/Field-Robotics-Lab/dave/wiki/BOP-Panel-Manipulation-Mission
   - [x] (#150) See above
   - [x] ~~Tutorial doesn’t say how to actually move the robot. Joystick presumably. Should link to a page detailing joystick control for RexROV and the Oberon7.~~
- [x] https://github.com/Field-Robotics-Lab/dave/wiki/Teleop-Bar-Retrieval
   - [x] This tutorial uses the same launch file (`uuv_dave.launch` I assumed and added) as the arm swapper tutorial, so should be set. Update: `uuv_dave.launch` had already been copied to `dave_demo.launch` and works.
   - [x] This tutorial has a bit more detail about the joystick. The two above should do the same, or they should all link to a page that talks about how to use the joystick. So far, I figured the left stick does z translation and rotation, and the right stick does x and y translation, for the base. I haven’t figured out how to move the actual arm.

**Comment by bsb808** [comment]
@mabelzhang 

1. Ideally we'd get `uuv_mating` and `uuv_dave` bits and pieces moved out of the `legacy` prior to 4.0.0.  Can you do that today?
2. The tf spam issue seems larger - agree we'll need to put that to post 4.0.0

**Comment by mabelzhang** [comment]
I can try to put them in the right places and others can check the locations in the PR.
I have a short meeting before noon PT and another thing due today, so I'll try.

**Comment by bsb808** [comment]
I'm flip-flopping.  I want to make the release deadline that is 16 minutes away, so let's push this to 4.0.1

**Comment by mabelzhang** [comment]
Okay. Yeah I'm getting crashes about TCP errors after moving `uuv_mating`. It's not gonna be done in the next 10 minutes.

**Comment by mabelzhang** [comment]
I've addressed everything in this ticket in #149 and #150, other than the tf spam, which isn't specific to manipulation tutorials and could be tracked either here or in a separate issue.

**Comment by mabelzhang** [comment]
Closing as all have been merged
