### ISSUE TITLE
Integrated World Checklist

### ISSUE THREAD

**Issue by Yadunund** [Field-Robotics-Lab/dave#215]
Ticket to track the progress of the integrated world

- [x] Select seabed model. 
  - https://github.com/Field-Robotics-Lab/dave/pull/203
- [ ] Add models from
  - [ ] https://app.ignitionrobotics.org/search;q=dave
  - [ ] https://github.com/Field-Robotics-Lab/dave/pull/194
  - [ ] https://github.com/Field-Robotics-Lab/dave/pull/209
- [ ] Incorporate electrical flying lead
  - [ ] From existing tutorial
  - [ ] Updates from https://github.com/Field-Robotics-Lab/dave/pull/189 
- [ ] Incorporate a mud pit with objects to drag around
- [ ] Incorporate bimanual demo
- [ ] Script to teleport UUV to various stations/demo sites
- [ ] [Optional] Incorporate multibeam demo
- [ ] [Optional] Incorporate multiple UUVs

**Comment by Yadunund** [comment]
Closing in favor of https://github.com/Field-Robotics-Lab/dave/pull/217
